# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))
provisionPath =  confDir + "/provision.sh"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "denisdeejay/Centos7-Apache2.4-Php5.4"
  
  config.vm.hostname = 'centos7'
  config.vm.box_check_update = false

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "./sol_imperialhotel_ec-site", "/var/www/sol_imperialhotel_ec-site"

  if File.exist? provisionPath then
    config.vm.provision "shell", path: provisionPath, privileged: false, keep_color: true
  end
end
